=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

# FIbonacci squence
# 1, 1, 2, 3, 5, 8,  13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946
# sum of even numbers
# 0, 0, 2, 2, 2, 10, 10, 10, 44, 44, 44, 188, 188, 188, 798
# amount of nomber
# 1, 2, 3, 4, 5, 6,  7,  8,  9,  10, 11, 12,  13,  14,  15
 class Fibonacci
    def initialize
       @cache = []
       @next_num = 1
       @prev_num  = 1
       @sum = 0
       @last_index = 2
    end
    
    def fibo_even_sum(number)   
        if number >= 2 && number <= @cache.size
            p "La suma se encunetra en el cache:"
            return @cache[number] if @cache[number]
            
           find_in_cache(number)
        elsif number >= 3
            p "Calculando"
           calculate_sum(number)
        else
            0
        end
    end

    def find_in_cache(number)
        current_posicion = (number - 1)
        loop do
            return @cache[current_posicion] if @cache[current_posicion]

            current_posicion -= 1
        end
    end

    def calculate_sum(number)
        (@last_index..(number - 1)).each do |i|
            @prev_num, @next_num = @next_num, @next_num + @prev_num
            if (@next_num % 2).zero?
                @sum += @next_num 
                @cache[i] = @sum
            end

            @last_index += 1
        end
        
        @sum
    end
end
    


fib = Fibonacci.new

p fib.fibo_even_sum(1)
p fib.fibo_even_sum(2)
p fib.fibo_even_sum(3)

p fib.fibo_even_sum(4)
p fib.fibo_even_sum(5)
p fib.fibo_even_sum(6)


p fib.fibo_even_sum(7)
p fib.fibo_even_sum(8)
p fib.fibo_even_sum(9)

p fib.fibo_even_sum(10)
p fib.fibo_even_sum(11)
p fib.fibo_even_sum(12)

p fib.fibo_even_sum(13)
p fib.fibo_even_sum(14)
p fib.fibo_even_sum(15)


    